---
- name: PowerMax Dell Playbook v1
  hosts: localhost
  gather_facts: no

  tasks:
  - name: Try running our new gather_facts module
    dellemc_powermax_gatherfacts:
      unispherehost: 10.126.70.19
      universion: "90"
      verifycert: False
      user: smc
      password: smc
    register: results

  - name: what JSON was returned
    debug:
      var: results

  - name: Provide serial number for next gather facts
    dellemc_powermax_gatherfacts:
      unispherehost: 10.126.70.19
      universion: "90"
      verifycert: False
      user: smc
      password: smc
      serial_no: "{{ results.Arrays[0] }}"
      tdev_volumes: False
      gather_subset:
        - vol
        - srp
        - sg
        - pg
        - host
        - hg
        - port
        - mv
        - rdf
    register: arrayresults

  - name: dump out to the screen
    debug:
      var: arrayresults

  - name: Write out data to a file
    copy:
      content: "{{ arrayresults }}"
      dest: "{{ results.Arrays[0] }}.dump"
