---
- name: PowerMax Dell Playbook v2
  hosts: localhost
  gather_facts: yes  # for ansible_date_time.date

  tasks:
  - name: Try running our new gather_facts module
    dellemc_powermax_gatherfacts:
      unispherehost: 10.126.70.19
      universion: "90" 
      verifycert: False
      user: smc
      password: smc
    register: results

  - name: Provide serial number for next gather facts
    dellemc_powermax_gatherfacts:
      unispherehost: 10.126.70.19
      universion: "90"
      verifycert: False
      user: smc
      password: smc
      serial_no: "{{ results.Arrays[0] }}"
      gather_subset:
        - vol
        - sg
        - srp
        - pg
        - host
        - hg
        - port
        - mv
        - rdf
    register: arrayresults

  - name: Create a location for PowerMax output
    file:
      state: directory
      dest: pmax_audit/

  - name: Create output file
    copy:
      dest: "pmax_audit/{{ results.Arrays[0] }}-{{ ansible_date_time.date }}.json"
      content: "{{ arrayresults }}"
